name: Build and Deploy (develop)

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven (skip tests)
        run: mvn -B package -Dmaven.test.skip=true



      - name: Publish JUnit Test Results (if needed)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: '**/surefire-reports/TEST-*.xml'
